# Generated by Django 3.2.9 on 2022-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveBigIntegerField(default=0)),
                ('expiration_date', models.DateField()),
                ('cvv_code', models.SmallIntegerField()),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
